
package com.epam.client.automatic;  

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomNumberGenerator", targetNamespace = "http://service.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandomNumberGenerator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "randomNumber", targetNamespace = "http://service.epam.com/", className = "com.epam.client.automatic.RandomNumber")
    @ResponseWrapper(localName = "randomNumberResponse", targetNamespace = "http://service.epam.com/", className = "com.epam.client.automatic.RandomNumberResponse")
    @Action(input = "http://service.epam.com/RandomNumberGenerator/randomNumberRequest", output = "http://service.epam.com/RandomNumberGenerator/randomNumberResponse")
    public int randomNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
